### ISSUE TITLE
transform data to DTO (e.g. name = first + last)?

### ISSUE THREAD

**Issue by wivaku** [WendellAdriel/laravel-validated-dto#22]
How do I transform data?

Example: `name` is a required field in my DTO, but my source array contains `firstName` and `lastName`.

```
$dto = App\DTOs\UserDTO::fromArray([
    // 'name' => 'John Doe',
    'firstName' => 'Jane',
    'lastName' => 'Doe',
]);
```

The following comes close, but forces me to set the rule for `name` to `sometimes` and feels like "abusing" the `defaults()` method.

```
class UserDTO extends ValidatedDTO
{
    public string $name;

    // properties from source data, not exposed in DTO
    protected string $firstName;
    protected string $lastName;

    protected function rules(): array
    {
        return [
            // have to set this to 'sometimes' even though the name is required
            'name' => ['sometimes', 'string'],

            // transformation properties needs to be listed here, even though they will not be exposed
            'firstName' => ['sometimes', 'string'],
            'lastName' => ['sometimes', 'string'],
        ];
    }

    protected function defaults(): array
    {
        return [
            'name' => $this->firstName .' '. $this->lastName,
        ];
    }
```

**Comment by WendellAdriel** [comment]
The DTOs provide a way to validate and cast the data, but this kind of transformation should happen outside the DTO. You can create the name property before instantiating the DTO, or leave the firstName and lastName in the DTO and use the values of these properties to create the name after the DTO is created since this is out of the scope of this package.

This can be achieved as you sent, adding it as a default value, but that will force you to put the sometimes rule on it. Depending on the context it can be a good solution since you know that it will always have the "computed" value of the two properties you need.
