### ISSUE TITLE
Ability to use ValidatedDTO within a request

### ISSUE THREAD

**Issue by cosmastech** [WendellAdriel/laravel-validated-dto#36]
I came across this package after looking at how Python's FastAPI uses Pydantic to validate form data. We use Laravel FormRequests heavily in our codebase, but there's always some things that seem to happen repeatedly.

1. We have to remember to use safe() or validated() when fetching data from requests
2. We check for an object's existence, then make a separate request to fetch that object from form input within the controller
3. Within the controller, we take the data and package up the params to send to a service. (Who likes service methods with 10 args? Who hasn't forgot to use type coercion? Ever ended up calling FormRequest@string('field_name, null) only to find out it's a Stringable object of an empty string, not null being returned 🤯 ?)

If we were able to make form requests nearly as simple to build as POPOs, with the power of PHP's strict typing, without redundancy, I think we would be in a great spot.

It would be great if we could build a `ValidatedDTOFormRequest` object that extends `Illuminate\Foundation\Http\FormRequest`, but let's us package up the request as a DTO directly. I see that ValidatedDTO::fromRequest exists, but then we are potentially running the validations twice. If the validation contains expensive DB queries, this would be less helpful.

Would be happy to work on this with you if you think it's something that might be beneficial as an addition to this package.

**Comment by WendellAdriel** [comment]
Hey @cosmastech thanks for reaching out, I'll be commenting below about your suggestion.

> It would be great if we could build a ValidatedDTOFormRequest object that extends Illuminate\Foundation\Http\FormRequest, but let's us package up the request as a DTO directly

The idea of the package is to decouple from the **Request** since the **DTOs** can be used in various different situations, not only for **Requests**, so this is not in the scope of this project.

> but then we are potentially running the validations twice. If the validation contains expensive DB queries, this would be less helpful.

When using this package, you don't need to use `Illuminate\Foundation\Http\FormRequest`, use the generic `\Illuminate\Http\Request` class instead as **[shown in the docs](https://wendell-adriel.gitbook.io/laravel-validated-dto/basics/creating-dto-instances#from-request-objects)**. The core idea of the package is to have a centralized place where the data is mapped and validated, so validations shouldn't be added in the **Requests**.

## Implementing DTOs with Requests

1. Create a DTO for the request, for example if you have a `CreateUserRequest`, create a `CreateUserDTO` and copy the `rules` method from the **Request** to the **DTO** class.
2. Rename your **Request** class to a **DTO** and update it to extend the `ValidatedDTO` instead, you'll have the `rules` method already defined, so just define the other needed methods.

After that, you just need to change the request in your controllers to the generic `\Illuminate\Http\Request` class and use the `fromRequest` method.
