### ISSUE TITLE
Breaking change v3.6.0

### ISSUE THREAD

**Issue by felixbessler** [WendellAdriel/laravel-validated-dto#81]
https://github.com/WendellAdriel/laravel-validated-dto/issues/77 was a pretty "big" breaking change for us, because we used `$this->data` in our DTOs. It is fair to say, we shouldn't but it makes it easier only retrieve the values we need for specific use cases, kinda like a custom DataTransformer. The working solution now is to switch to `$this->validatedData`. 

I tried to make a PR for the docs, but I couldn't find the right place for that and I'm also looking at `private function buildDataForExport()`. 🤔 If we could make that protected, it might be the even better function for our use case and maybe others that are trying to create their own DataTransformers? Is this something you are open to, then I could make a PR and write a little thing in the docs.

**Comment by WendellAdriel** [comment]
Yeah, you shouldn't be using `$this->data` 😅 
This property is not documented anywhere so this shouldn't be being used and that's why I didn't consider this a breaking change.

I think that your proposed solution is good.
Please open a PR for the code and the docs for it, I think it's going to be a great addition to the package! 💪

**Comment by WendellAdriel** [comment]
Hey @felixbessler the v3.7.0 has already been released with your contributions and the docs are also updated, thank you so much! 💪 🔥 😉

**Comment by felixbessler** [comment]
Thanks for making this awesome package and I will be using this change already next week. 😅
